# name of my workflow
name: Merge Pull Requests

# Setting up trigger
on:
  push:
    branches:
      - "feat/intro"

# Defining jobs
jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise Pull Requests
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "feat/intro"
          base: master
          title: "Pull Request Creation"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}
          body: This is to show automatic pull request creation
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: false